
INSERT INTO INVENTRY (ID, NAME,QTY,PRICE) VALUES (1, 'item1',10,100);
INSERT INTO INVENTRY (ID, NAME,QTY,PRICE) VALUES (2, 'item2',20,150);
INSERT INTO INVENTRY (ID, NAME,QTY,PRICE) VALUES (3, 'item3',30,120);
INSERT INTO INVENTRY (ID, NAME,QTY,PRICE) VALUES (4, 'item4',25,200);
INSERT INTO INVENTRY (ID, NAME,QTY,PRICE) VALUES (5, 'item5',95,10);